[package]
name = "propfi"
version = "0.1.0"
description = "PropFi: Tokenized Real Estate on Solana"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "propfi"

[dependencies]
anchor-lang = "0.28.0"
anchor-spl = "0.28.0"
